name: Preprocess Dataset

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Untuk menentuka OS tempat workflow dijalankan
jobs:
  run-preprocessing:
    runs-on: ubuntu-latest

    # Mengambil isi repo agar bisa di akses di workflow
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Menyiapkan versi Python yang dibutuhkan
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"

      # Menginstal semua library dari  requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Menjalankan file automate_Satriana.py
      - name: Run preprocessing script
        run: |
          python preprocessing/automate_Satriana.py \
            --input_path studentsperformance_raw/StudentsPerformance.csv \
            --output_path preprocessing/studentsperformance_preprocessing/StudentsPerformance_preprocessing.csv

      - name: List output folder
        run: ls -la preprocessing/studentsperformance_preprocessing || true

      # untuk menyimpan hasil ke Artifact Github
      - name: Upload processed dataset as artifact
        uses: actions/upload-artifact@v4
        with:
          name: students-processed
          path: preprocessing/studentsperformance_preprocessing/StudentsPerformance_preprocessing.csv

      # Meng-commit hasil ke repo supaya muncul di Github
      - name: Commit and push preprocessed file
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add preprocessing/studentsperformance_preprocessing/StudentsPerformance_preprocessing.csv
          git commit -m "Add latest preprocessed dataset" || echo "No changes to commit"
          git push
